name: crx

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache fteqcc
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: |
            fteqcc64.exe
          key: fteqcc

      - name: Fetch fteqcc (Windows)
        run: |
          curl -o fteqcc_win64.zip https://www.fteqcc.org/dl/fteqcc_win64.zip
          tar -xf fteqcc_win64.zip --include=fteqcc64.exe
        if: steps.cache-dependencies.outputs.cache-hit != 'true'

      - name: Compile CRx
        run: .\fteqcc64.exe -src src

      - name: Ensure release directory exists
        run: |
          if (!(Test-Path -Path "release")) {
            mkdir release
          }

      - name: Collect artifacts
        run: |
          move src\progs.dat release\
          move src\csprogs.dat release\
      - uses: actions/upload-artifact@v4
        with:
          name: CRx
          path: |
            release\*
