name: crx

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Docker with Required GLIBC
        run: |
          docker run --rm \
            -v "$(pwd):/workspace" \
            -w /workspace \
            ubuntu:22.10 \
            bash -c "apt update && apt install -y curl unzip libc6 && curl -Ofteqcc.zip https://www.fteqcc.org/dl/fteqcc_linux64.zip && unzip fteqcc_linux64.zip fteqcc64 && ./fteqcc64 -src src"

      - name: Collect artifacts
        run: |
          mv src/progs.dat release/
          mv src/csprogs.dat release/
      - uses: actions/upload-artifact@v3
        with:
          name: crmod-plus
          path: |
            release/*
